// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage;
using Microsoft.EntityFrameworkCore.Storage.Internal;
using System;
using TraumaNetwork;

namespace TraumaNetwork.Migrations
{
    [DbContext(typeof(TraumaContext))]
    [Migration("20180407183242_r1003")]
    partial class r1003
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.0.2-rtm-10011")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("TraumaNetwork.AgeGroup", b =>
                {
                    b.Property<Guid>("ID")
                        .ValueGeneratedOnAdd()
                        .HasDefaultValueSql("newid()");

                    b.Property<string>("Name");

                    b.Property<int>("Order");

                    b.HasKey("ID");

                    b.ToTable("AgeGroup");
                });

            modelBuilder.Entity("TraumaNetwork.Agency", b =>
                {
                    b.Property<Guid>("ID")
                        .ValueGeneratedOnAdd()
                        .HasDefaultValueSql("newid()");

                    b.Property<string>("Email");

                    b.Property<string>("Name");

                    b.Property<string>("Phone");

                    b.Property<string>("Website");

                    b.HasKey("ID");

                    b.ToTable("Agencies");
                });

            modelBuilder.Entity("TraumaNetwork.AgencyAgeGroup", b =>
                {
                    b.Property<Guid>("AgencyID");

                    b.Property<Guid>("AgeGroupID");

                    b.HasKey("AgencyID", "AgeGroupID");

                    b.HasAlternateKey("AgeGroupID", "AgencyID");

                    b.ToTable("AgencyAgeGroup");
                });

            modelBuilder.Entity("TraumaNetwork.AgencyCategory", b =>
                {
                    b.Property<Guid>("AgencyID");

                    b.Property<Guid>("CategoryID");

                    b.HasKey("AgencyID", "CategoryID");

                    b.HasIndex("CategoryID");

                    b.ToTable("AgencyCategory");
                });

            modelBuilder.Entity("TraumaNetwork.AgencyFinancialPlan", b =>
                {
                    b.Property<Guid>("AgencyID");

                    b.Property<Guid>("FinancialID");

                    b.HasKey("AgencyID", "FinancialID");

                    b.HasIndex("FinancialID");

                    b.ToTable("AgencyFinancialPlan");
                });

            modelBuilder.Entity("TraumaNetwork.AgencyLocation", b =>
                {
                    b.Property<Guid>("ID")
                        .ValueGeneratedOnAdd()
                        .HasDefaultValueSql("newid()");

                    b.Property<string>("Address1");

                    b.Property<string>("Address2");

                    b.Property<Guid>("AgencyID");

                    b.Property<string>("City");

                    b.Property<string>("State");

                    b.Property<string>("Zip");

                    b.HasKey("ID");

                    b.HasIndex("AgencyID");

                    b.ToTable("AgencyLocation");
                });

            modelBuilder.Entity("TraumaNetwork.AgencyService", b =>
                {
                    b.Property<Guid>("AgencyID");

                    b.Property<Guid>("ServiceID");

                    b.Property<string>("TypicalResponseTime");

                    b.HasKey("AgencyID", "ServiceID");

                    b.HasIndex("ServiceID");

                    b.ToTable("AgencyService");
                });

            modelBuilder.Entity("TraumaNetwork.AgencySpecialty", b =>
                {
                    b.Property<Guid>("AgencyID");

                    b.Property<Guid>("SpecialtyID");

                    b.HasKey("AgencyID", "SpecialtyID");

                    b.HasIndex("SpecialtyID");

                    b.ToTable("AgencySpecialty");
                });

            modelBuilder.Entity("TraumaNetwork.Category", b =>
                {
                    b.Property<Guid>("ID")
                        .ValueGeneratedOnAdd()
                        .HasDefaultValueSql("newid()");

                    b.Property<string>("Name");

                    b.Property<int>("Order");

                    b.HasKey("ID");

                    b.ToTable("Category");
                });

            modelBuilder.Entity("TraumaNetwork.FinancialPlan", b =>
                {
                    b.Property<Guid>("ID")
                        .ValueGeneratedOnAdd()
                        .HasDefaultValueSql("newid()");

                    b.Property<string>("Name");

                    b.Property<int>("Order");

                    b.HasKey("ID");

                    b.ToTable("FinancialPlan");
                });

            modelBuilder.Entity("TraumaNetwork.Service", b =>
                {
                    b.Property<Guid>("ID")
                        .ValueGeneratedOnAdd()
                        .HasDefaultValueSql("newid()");

                    b.Property<string>("Name");

                    b.Property<int>("Order");

                    b.HasKey("ID");

                    b.ToTable("Service");
                });

            modelBuilder.Entity("TraumaNetwork.Specialty", b =>
                {
                    b.Property<Guid>("ID")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Name");

                    b.Property<int>("Order");

                    b.HasKey("ID");

                    b.ToTable("Specialty");
                });

            modelBuilder.Entity("TraumaNetwork.AgencyAgeGroup", b =>
                {
                    b.HasOne("TraumaNetwork.AgeGroup", "AgeGroup")
                        .WithMany("Agencies")
                        .HasForeignKey("AgeGroupID")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("TraumaNetwork.Agency", "Agency")
                        .WithMany("AgeGroups")
                        .HasForeignKey("AgencyID")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("TraumaNetwork.AgencyCategory", b =>
                {
                    b.HasOne("TraumaNetwork.Agency", "Agency")
                        .WithMany("Categories")
                        .HasForeignKey("AgencyID")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("TraumaNetwork.Category", "Category")
                        .WithMany("Agencies")
                        .HasForeignKey("CategoryID")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("TraumaNetwork.AgencyFinancialPlan", b =>
                {
                    b.HasOne("TraumaNetwork.Agency", "Agency")
                        .WithMany("FinancialPlans")
                        .HasForeignKey("AgencyID")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("TraumaNetwork.FinancialPlan", "Financial")
                        .WithMany("Agencies")
                        .HasForeignKey("FinancialID")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("TraumaNetwork.AgencyLocation", b =>
                {
                    b.HasOne("TraumaNetwork.Agency", "Agency")
                        .WithMany("Locations")
                        .HasForeignKey("AgencyID")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("TraumaNetwork.AgencyService", b =>
                {
                    b.HasOne("TraumaNetwork.Agency", "Agency")
                        .WithMany("Services")
                        .HasForeignKey("AgencyID")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("TraumaNetwork.Service", "Service")
                        .WithMany("Agencies")
                        .HasForeignKey("ServiceID")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("TraumaNetwork.AgencySpecialty", b =>
                {
                    b.HasOne("TraumaNetwork.Agency", "Agency")
                        .WithMany("Specialties")
                        .HasForeignKey("AgencyID")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("TraumaNetwork.Specialty", "Specialty")
                        .WithMany("Agencies")
                        .HasForeignKey("SpecialtyID")
                        .OnDelete(DeleteBehavior.Cascade);
                });
#pragma warning restore 612, 618
        }
    }
}
